QUOTES = [
    "Treat global variables like someone has a knife to your throat.",
        "Hate working with undocumented code? Get into the habit of writing comments to enforce better habits for others to adopt.",
    "Learn to start one programming language and stick with that. Build a solid foundation first.",
    "Don't choke up on syntax. It hardly matters. Try to work on your logics and patterns.",
    "Use a Coding Standard to increase readibility of code.",
    "Write Useful Comments to open doors for collaboration.",
    "Stuck on a problem? Write it out. It'll open up different angles that you couldn't see before.",
    "Set some time aside to work on technical debt.",
    "When naming variables, use meaningful names.",
    "Use version control software to help manage your source code better.",
    "The most disastrous thing that you can ever learn is your first programming language.",
    "In your own time, work on your own code. Do something fun. Do something pointless. Abandon with abandon. There is no pressure to finish anything other than the pressure you put on yourself",
    "Don’t rely on coffee or energy drinks to keep you ‘buzzing’. This is a clear indication that you’re too tired to do good work.",
    "Don't choke up on syntax. It hardly matters. Try to work on your logics and patterns.",
    "Do not repeat code: use loops or functions instead",
    "Group global variables into records, objects or structures",
    "Throw yourself in the deep end. You'll come out stronger and more confident.",
    "Learning to code is learning to create and innovate.",
]